[launch_options]
generate_sky_heightmap = true
generate_sky_texture = true

generate_terrain_heightmap = true
generate_terrain_texture = true  # uniquement pris en compte si precedent est "true"

displayer_path = "C:\\Users\\Timelam\\rp\\mapgeneration\\displayer\\launcher.cmd"

[generation_options]
seed = 51462

terrain_power_of_two = 12  # taille du terrain: 2^n + 1
mesh_power_of_two = 10  # taille du mesh: 2^rn + 1

template_power_of_two = 6

max_terrain_height = 102.0
irregularity = 1.0  # réel entre 0.0 et 1.0: irregularite du terrain

sun_angle = 70.0  # réel entre 0.0 et 89.0: angle du soleil en degre par rapport a l'horizon
sun_size = 0.002
atmosphere_radius = 104.0
planet_radius = 99.0

ambient_sky_light = 0.6

shadow_direction = 3

number_of_erosion_iterations = 127000
inertia = 0.05
radius = 4
capacity_factor = 6.0



