[launch_options]
generate_sky_heightmap = false
generate_sky_texture = false

generate_terrain_heightmap = true
generate_terrain_texture = true  # uniquement pris en compte si precedent est "true"

[generation_options]
seed = 51462

max_terrain_height = 250.0
irregularity = 0.4  # réel entre 0.0 et 1.0: irregularite du terrain

sun_angle = 10.0  # réel entre 0.0 et 89.0: angle du soleil en degre par rapport a l'horizon
sun_size = 0.002
atmosphere_radius = 104.0
planet_radius = 99.0

ambient_sky_light = 0.6

shadow_direction = 3



