[launch_options]

generate_sky_heightmap = true
generate_sky_texture = true

generate_terrain_heightmap = true
generate_terrain_texture = true  # uniquement pris en compte si precedent est "true"

displayer_path = "C:\\Users\\Hélène Le Berre\\rp\\mapgeneration\\displayer\\launcher.cmd"




[generation_options]

# base generation options
seed = 51462

terrain_power_of_two = 12  # taille du terrain: 2^n + 1
mesh_power_of_two = 10  # taille du mesh: 2^rn + 1

template_power_of_two = 6


# diamond-square
max_terrain_height = 150.0
irregularity = 0.5  # réel entre 0.0 et 1.0: irregularite du terrain


# sky generation
sun_angle = 0.0  # réel entre 0.0 et 89.0: angle du soleil en degre par rapport a l'horizon
sun_size = 0.002
atmosphere_radius = 104.0
planet_radius = 99.0

ambient_sky_light = 0.6


# terrain texturing
shadow_direction = 3


# terrain deformation
number_of_erosion_iterations = 127000
inertia = 0.01
radius = 3
capacity_factor = 120.0
initial_lifetime = 10

# ----------  broken  -------------------
number_of_erosion_iterations_2 = 10000
inertia_2 = 0.01
radius_2 = 10
capacity_factor_2 = 20.0
# ---------------------------------------

# terrain coloration
rock_threshold = 0.5


